### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by wesoudshoorn**
Cleanup the blog layout a bit.

- new border under H2 for some structure
- new styling for code blocks (light!)
- little border to the left of subnav
- removed the capitalized titles

image

### CODE REVIEW

**Comment by roytomeij** [comment]
Code looks good. Contrast between code comments and the background seems a bit low on my screen.

**Comment by wesoudshoorn** [comment]
Should be better like this (blur is because of the screenshots)
image

**Comment by roytomeij** [comment]
👍

**Comment by thijsc** [comment]
:+1: Looks good

**Pull request merged**
