### PR TITLE
Add "on this page" section

### PR DESCRIPTION
**Pull request by jonasbrinkhoff**
Adds an "on this page" section to the documentation

**To-Do**
- [x] Hide when empty
- [x] Improve font size
- ~[ ] Make it sticky~ Will be done in a separate PR

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@jonasbrinkhoff I just pushed a thing that automates the generation of the "on this page"

**Comment by wesoudshoorn** [comment]
@jonasbrinkhoff can you edit the description so people know what this does? It currently only shows the WIP description.

I'll review it now :-)

**Comment by jonasbrinkhoff** [comment]
> Visually, I think we need to work on some alignment

Yes agreed. But it's quite hard to with all the moving parts in different PRs. Wanted to give it another design treatment once all major changes (sidenav, search bar, content and "on this page") are merged. 

> Making it sticky

Yes good idea, will do it!

> Two-line headers. Should we add a little separator between items to make this more clear? Or adjust the line-height/font-size/margins?

To me it seems quite clear. On a more general note, I think we should also try to keep headings short to make them easier to scan. So maybe that's a smarter way to solve the problem?

> Font-size

Yes, agreed. Will work on it.

> New header?

The PR is already done, just waiting for the review :)

**Comment by jonasbrinkhoff** [comment]
Making it sticky requires some changes in the general layout of the page. Will do that in a separate PR.

**Pull request merged**
