### PR TITLE
New side navigation design

### LINKED ISSUE #57: Losing scroll position on refresh
When I refresh a page the scroll position resets and I get scrolled back up to the top of a page. Really annoying since I refresh the page a lot nowadays, updating the docs.

### PR DESCRIPTION
**Pull request by wesoudshoorn**
Trying to improve the docs and resolve the scroll issue by refactoring the layout a bit. 

## Things I am trying to improve
- Navigation is long and overview is hard in 1 look, toggling navigation items might help
- Refactor some CSS to make typography / header it consistent with the blog

## Some issues
- [x] Switching between pages in the documentation resets your opened / closed navigation items. Need a dev to look at this
- [x] I wrecked the responsiveness

Closes #57

### CODE REVIEW

**Comment by tombruijn** [comment]
Ah I thought we decided to show everything always. So that a look through the nav would tell you exactly all the content we have. Is the list already becoming too long?

But yeah 👍  for collapsing content. When you don't use Ruby or Elixir you can collapse all the content for it.

Right now, some content is *gone*. What's your idea for the sub-levels under sections?

appsignal documentation 2016-11-04 12-15-52


We can save the collapsed/uncollapsed sections in a cookie with some JS.

**Comment by wesoudshoorn** [comment]
Oh accidentally hid the subnav 😆 

**This would be how you land on a page by default. Current section open.**
image

**If you open up everything by default, the content already gets quit long.**
I might have said otherwise before, but seeing it like this does not make it easier to scan for me.
image

**Comment by matsimitsu** [comment]
We should be able to detect an active sub-section from the url and open that part of the menu when navigating.

**Comment by thijsc** [comment]
What is the status of this?

**Comment by tombruijn** [comment]
@wesoudshoorn needs to fix the responsiveness and we need to fix opening the right topic/category block on load.

**Comment by wesoudshoorn** [comment]
I made it responsive now @tombruijn @thijsc and the only thing we need to do is opening / closing the right sections. This is something a dev can do :)

**Comment by tombruijn** [comment]
Added logic to toggle the navigation menus with javascript. Let me know what you think

**Pull request merged**
