### PR TITLE
Node.js docs update

### PR DESCRIPTION
**Pull request by xadamy**
Big docs update covering all the features so far. Apologies for the size.

## TODO:

- [x] Intro for tracing
- [x] Abstract span/tracing diagram (@wesoudshoorn @jonasbrinkhoff )

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Is this one ready for review?

**Comment by xadamy** [comment]
@jeffkreeftmeijer Still waiting for some content to be added, but please feel free to review what's been written up to now!

**Comment by jonasbrinkhoff** [comment]
@xadamy do you still need help with the abstract span/tracing diagram?

**Comment by xadamy** [comment]
@jonasbrinkhoff Yes please (if you have time)! 👍

**Pull request merged**
