### PR TITLE
Add shared design language

### PR DESCRIPTION
**Pull request by wesoudshoorn**
This pull request is part of an effort to consolidate some design language in CSS so we can share it over multiple projects (docs, blog, -server).

For now, it just shares typography, variables, mixins. The end-goal is sharing the header, but this setup is a nice milestone!

### CODE REVIEW

**Comment by tombruijn** [comment]
The navigation `<sup>` labels are missing a highlight color. See "DEPRECATED" in the image below. Left is this PR, Right is docs.appsignal.com.

image

**Comment by tombruijn** [comment]
The "boxes" at the bottom of the page are quite low contrast in this PR

image

**Comment by tombruijn** [comment]
I think some pages can look a bit "dull". The combination of the gray header, gray headings and gray tables looks a bit meh.. I liked the blue-ish tones.

image

Otherwise I don't see any other regressions

**Comment by wesoudshoorn** [comment]
@tombruijn the next step is the new header, which will make it look more like:

image

I will refactor the sidebar later to match its design.

**Pull request merged**
