### PR TITLE
Remove Ruby's garbage collection config option

### PR DESCRIPTION
**Pull request by shairyar**
Removing Ruby's garbage collection config option since the feature still requires some work.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@shairyar Is this something that came out of a discussion within the Integrations team? I don't know enough about the integration to be able to say "Yes this needs more work" I'll add @tombruijn to this; He knows more about this.

**Comment by shairyar** [comment]
@thijsc and I were discussing this in the [slack](https://appsignal.slack.com/archives/CNPP953E2/p1611125226001100) today

**Review by thijsc — APPROVED** [review]

**Review by tombruijn — APPROVED** [review]
Should we also remove it from the gem itself, or just hide it from the docs like this?

**Comment by shairyar** [comment]
I am guessing if it is only the dashboard changes that are pending we can leave it in otherwise remove it?

**Pull request merged**
