### PR TITLE
Add search to docs

### PR DESCRIPTION
**Pull request by jvanbaarsen**
This adds the search field for the docs search. It doesn't have any styling. I discussed with @wesoudshoorn and he indicates that he has time to work on styling this next week.

**Todo**
- [x] Remove font-awesome icons + css from navigation
- [x] Responsiveness of search results

**Design changes**
- Removed icons from navigation
- Split up the navigation into sections for easier visual parsing of structure

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@wesoudshoorn 	When would you have time to look at this with me?

**Comment by wesoudshoorn** [comment]
@jvanbaarsen I think we can do this on Wednesday next week. Finishing up the Dev Dilemmas first.

**Comment by jvanbaarsen** [comment]
@wesoudshoorn Sorry I missed your comment. This week somewhere? I'm off on Thursdays from now on.

**Comment by wesoudshoorn** [comment]
Just fixed some layout issues.

The layout on mobile is not working great yet, the result box from Algolia is broken.

Also, we'll have to check the pricing; hoping we can get on the $29 plan, that would be a good price to solve this issue. Their next tier is $499, which is way too much for this usecase

**Comment by jvanbaarsen** [comment]
@wesoudshoorn I checked the pricing page, but I cannot find anything about responsiveness on there. Can you point me to that page?

**Comment by wesoudshoorn** [comment]
Responsiveness and pricing are two separate issues :) 

**Pricing**
https://www.algolia.com/pricing/

**Responsive on small screens**
image

**Comment by jvanbaarsen** [comment]
@wesoudshoorn Ah sorry, I thought you meant the responsiveness would be fixed by paying.

**Comment by jvanbaarsen** [comment]
@wesoudshoorn Shall we take some time next week to look at the next steps for this?

**Comment by tombruijn** [comment]
@jvanbaarsen @wesoudshoorn I made a quick fix for smaller screens. Is anything else blocking? We'd like to ship this.

**Comment by jvanbaarsen** [comment]
@tombruijn 	I'll put it on my list for this week to double check.

**Comment by jvanbaarsen** [comment]
@tombruijn 	Nice, just tested this locally, everything is working as expected :-) Can you do a final review? I would love to get this deployed this week.

**Pull request merged**
