### PR TITLE
Add permission table

### PR DESCRIPTION
**Pull request by noccor**
Relates to issue #580

### CODE REVIEW

**Comment by noccor** [comment]
@wesoudshoorn does this cover everything? I feel like this is the most logical location for it, but could also make it it's own page.

**Comment by wesoudshoorn** [comment]
I think that either @matsimitsu or @jvanbaarsen could help by searching for some permission checks in Ruby / React. This would make it easier to know exactly what people can and can not do. 

For example, I think that users can _add_ a new site, but they can't roll API keys or delete a site?

**Comment by wesoudshoorn** [comment]
Converted to draft until @noccor is back

**Comment by wesoudshoorn** [comment]
@noccor I removed us as reviewers because we kept getting reminders :)

**Pull request closed without merging**
