### PR TITLE
Add new installation instructions for standalone agent

### PR DESCRIPTION
**Pull request by thijsc**
Updated instructions using apt.

### CODE REVIEW

**Comment by thijsc** [comment]
@matsimitsu can you re-review? I added a page about StatsD.

**Comment by thijsc** [comment]
Merging, if anyone wants to tweak stuff feel free to open a PR :-)

**Comment by jeffkreeftmeijer** [comment]
Ah, merged already. Looks great, but the StatsD page could use a link to the custom metrics page to help explain what users can do with this data.

**Comment by thijsc** [comment]
Added a link in `master`

**Pull request merged**
